Main:
  files:
  - $all
  - "!$test"
  allow:
  - $gostd
  - github.com/stader-labs/stader-node/stader-lib/node
  - github.com/stader-labs/stader-node/shared/utils/eth1
  - github.com/stader-labs/stader-node/shared/types/stader-backend
  - github.com/stader-labs/stader-node/shared/utils/cli
  deny:
    reflect: Please don't use reflect package
Test:
  files:
  - $test
  allow:
  - $gostd
  - github.com/stretchr/testify
  deny:
    reflect: Please don't use reflect package